version: '3.8'

services:
  backend:
    image: darkata/bidmaster-backend:latest
    build: ./backend
    container_name: bidmaster-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000

  frontend:
    image: darkata/bidmaster-frontend:latest
    build: ./frontend
    container_name: bidmaster-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend
